name: goggles-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cython=0.29.22
  - matplotlib
  - scikit-image
  - black
  - isort
  - pytest
  - pip
  - pip:
    - pyqt5==5.15.4
    - opencv-python
    - dearpygui
